# ============================================================
# ZK-NEXUS → GOOGLE DRIVE SYNC SETUP SCRIPT
# Target: zubairisa10@gmail.com / "ZK Nexus Workspace" folder
# Generated by Antigravity on 2026-08-05
# ============================================================

# ── Config ──────────────────────────────────────────────────
$REMOTE_NAME    = "zknexus-gdrive"
$GDRIVE_EMAIL   = "zubairisa10@gmail.com"
$GDRIVE_FOLDER  = "ZK Nexus Workspace"
$LOCAL_ROOT     = "C:\Users\Dell\Documents\Projects ZK Nexus"
$LOG_FILE       = "$LOCAL_ROOT\08_Logs\gdrive-sync-$(Get-Date -Format 'yyyyMMdd-HHmm').log"

# Refresh PATH so rclone is found after winget install
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" +
            [System.Environment]::GetEnvironmentVariable("Path","User")

# ── Verify rclone ────────────────────────────────────────────
Write-Host "`n🔧 Checking rclone..." -ForegroundColor Cyan
$rcloneVersion = rclone version 2>&1 | Select-Object -First 1
if (-not $rcloneVersion) {
    Write-Host "❌ rclone not found. Please install it: winget install Rclone.Rclone" -ForegroundColor Red
    exit 1
}
Write-Host "✅ $rcloneVersion" -ForegroundColor Green

# ── Check if remote already configured ──────────────────────
$existingRemotes = rclone listremotes 2>&1
if ($existingRemotes -like "*${REMOTE_NAME}*") {
    Write-Host "✅ Remote '$REMOTE_NAME' already configured. Skipping OAuth setup." -ForegroundColor Green
} else {
    Write-Host "`n🔐 Configuring Google Drive remote '$REMOTE_NAME'..." -ForegroundColor Cyan
    Write-Host "   → This will open your browser for Google OAuth login." -ForegroundColor Yellow
    Write-Host "   → Sign in as: $GDRIVE_EMAIL" -ForegroundColor Yellow
    Write-Host ""

    # Run rclone config create (interactive OAuth — opens browser)
    rclone config create $REMOTE_NAME drive `
        scope "drive" `
        use_trash false

    Write-Host "`n✅ Remote configured!" -ForegroundColor Green
}

# ── Ensure target folder exists on Drive ────────────────────
Write-Host "`n📁 Ensuring '$GDRIVE_FOLDER' exists on Google Drive..." -ForegroundColor Cyan
rclone mkdir "${REMOTE_NAME}:${GDRIVE_FOLDER}" 2>&1
Write-Host "✅ Target folder ready." -ForegroundColor Green

# ── Count local files before sync ───────────────────────────
Write-Host "`n📊 Counting local files..." -ForegroundColor Cyan
$allFiles = Get-ChildItem -Path $LOCAL_ROOT -Recurse -File |
    Where-Object { $_.FullName -notmatch '\\\.git\\|\\\.agents\\|\\\.snapshots\\' }
$totalFiles = $allFiles.Count
Write-Host "   → $totalFiles files found locally" -ForegroundColor White

# ── Run rclone sync ─────────────────────────────────────────
Write-Host "`n🚀 Starting sync: Local → Google Drive '$GDRIVE_FOLDER'..." -ForegroundColor Cyan
Write-Host "   This may take a few minutes depending on file count and size.`n"

$syncStart = Get-Date

rclone copy $LOCAL_ROOT "${REMOTE_NAME}:${GDRIVE_FOLDER}" `
    --exclude ".git/**" `
    --exclude ".agents/**" `
    --exclude ".snapshots/**" `
    --exclude "*.tmp" `
    --progress `
    --transfers 8 `
    --checkers 16 `
    --log-file $LOG_FILE `
    --log-level INFO `
    2>&1

$syncEnd   = Get-Date
$duration  = [math]::Round(($syncEnd - $syncStart).TotalSeconds, 1)

# ── Verify: list Drive files ─────────────────────────────────
Write-Host "`n🔍 Verifying upload on Google Drive..." -ForegroundColor Cyan
$driveCount = (rclone ls "${REMOTE_NAME}:${GDRIVE_FOLDER}" 2>&1 | Measure-Object -Line).Lines
Write-Host "   → $driveCount file entries found on Drive" -ForegroundColor White

# ── Summary Report ───────────────────────────────────────────
$report = @"

╔══════════════════════════════════════════════════════════════╗
║           ZK-NEXUS → GOOGLE DRIVE SYNC REPORT               ║
╠══════════════════════════════════════════════════════════════╣
║  Timestamp  : $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')                       ║
║  Account    : $GDRIVE_EMAIL                  ║
║  GDrive Dir : $GDRIVE_FOLDER                            ║
╠══════════════════════════════════════════════════════════════╣
║  Local Files   : $totalFiles                                        ║
║  Drive Files   : $driveCount                                        ║
║  Duration      : ${duration}s                                      ║
║  Log File      : $LOG_FILE  ║
╠══════════════════════════════════════════════════════════════╣
║  Folders synced:                                             ║
║    ✅ 00_Command Center                                      ║
║    ✅ 01_Business                                            ║
║    ✅ 02_Projects                                            ║
║    ✅ 03_Knowledge                                           ║
║    ✅ 04_Workforce                                           ║
║    ✅ 05_Systems                                             ║
║    ✅ 06_Resources                                           ║
║    ✅ 07_Templates                                           ║
║    ✅ 08_Logs                                                ║
║    ✅ 99_Archive                                             ║
╚══════════════════════════════════════════════════════════════╝
"@

Write-Host $report -ForegroundColor Green

# Write report to log
$report | Out-File -FilePath "$LOCAL_ROOT\08_Logs\gdrive-sync-report-$(Get-Date -Format 'yyyyMMdd-HHmm').txt" -Encoding UTF8

Write-Host "📄 Full log saved to: $LOG_FILE" -ForegroundColor DarkGray
Write-Host "`n✅ Sync complete! Your ZK-Nexus workspace is now on Google Drive." -ForegroundColor Green
Write-Host "   Open Drive: https://drive.google.com/drive/folders" -ForegroundColor Blue
